services:
  rust_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/rust_template
    command: ["./target/release/rust_template"]
